/**
 * JetBrains Plugin Manifest Generator
 *
 * Generates the plugin.xml file required for JetBrains IDE plugins.
 * This file is placed in resources/META-INF/plugin.xml
 *
 * References:
 * - https://plugins.jetbrains.com/docs/intellij/plugin-configuration-file.html
 * - https://plugins.jetbrains.com/docs/intellij/developing-themes.html
 */

import { Meta } from "../../shared/meta";
import { ThemeRegistryEntry } from "../../shared/theme-registry";

/**
 * Generate the plugin.xml manifest file content
 *
 * @param themes - Array of theme registry entries
 * @param version - Plugin version
 * @returns XML string for plugin.xml
 */
export function generatePluginXml(
  themes: ThemeRegistryEntry[],
  version: string,
): string {
  const themeProviders = themes
    .map((entry) => {
      const themeId = escapeXml(`${Meta.slug}-${entry.slug}`);
      // Path is relative to JAR root - no /themes/ prefix needed
      const themePath = escapeXml(`/${Meta.slug}-${entry.slug}.theme.json`);

      return `    <themeProvider
      id="${themeId}"
      path="${themePath}"
    />`;
    })
    .join("\n");

  const categoriesHtml = Meta.categories
    .map((c) => `<li><strong>${escapeXml(c.name)}</strong> - ${escapeXml(c.description)}</li>`)
    .join("\n      ");

  return `<!--
  ${Meta.name} for JetBrains IDEs
  Generated by Bearded Theme Build System
  ${Meta.urls.github}
-->
<idea-plugin>
  <id>com.beardedtheme.jetbrains</id>
  <name>${Meta.name}</name>
  <version>${version}</version>
  <vendor
    email="${Meta.author.email}"
    url="${Meta.urls.github}"
  >${Meta.author.name}</vendor>

  <description><![CDATA[
    <h1>${Meta.name}</h1>
    <p>${Meta.description} A collection of carefully crafted color themes for your IDE.</p>

    <h2>Features</h2>
    <ul>
      <li>${themes.length}+ theme variants including dark, light, and high contrast options</li>
      <li>Carefully designed color palettes for reduced eye strain</li>
      <li>Consistent syntax highlighting across all supported languages</li>
      <li>Support for the new Islands UI theme style</li>
    </ul>

    <h2>Theme Categories</h2>
    <ul>
      ${categoriesHtml}
    </ul>

    <h2>Links</h2>
    <ul>
      <li><a href="${Meta.urls.github}">GitHub Repository</a></li>
      <li><a href="${Meta.urls.issues}">Report Issues</a></li>
      <li><a href="${Meta.urls.marketplace.vscode}">VS Code Version</a></li>
    </ul>
  ]]></description>

  <change-notes><![CDATA[
    <p>See the <a href="${Meta.urls.github}/releases">GitHub Releases</a> for full changelog.</p>
  ]]></change-notes>

  <idea-version since-build="241"/>

  <depends>com.intellij.modules.platform</depends>

  <extensions defaultExtensionNs="com.intellij">
${themeProviders}
  </extensions>
</idea-plugin>
`;
}

/**
 * Generate a list of theme entries for the plugin
 *
 * @param themes - Array of theme registry entries
 * @returns Array of theme information objects
 */
export function getThemeList(
  themes: ThemeRegistryEntry[],
): Array<{
  dark: boolean;
  id: string;
  name: string;
  path: string;
}> {
  return themes.map((entry) => ({
    dark: !entry.options.light,
    id: `${Meta.slug}-${entry.slug}`,
    name: `${Meta.name} ${entry.name}`,
    path: `/${Meta.slug}-${entry.slug}.theme.json`,
  }));
}

/**
 * Escape special XML characters in a string
 *
 * @param str - String to escape
 * @returns XML-safe string
 */
function escapeXml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}
