/**
 * JetBrains Plugin Manifest Generator
 *
 * Generates the plugin.xml file required for JetBrains IDE plugins.
 * This file is placed in resources/META-INF/plugin.xml
 *
 * References:
 * - https://plugins.jetbrains.com/docs/intellij/plugin-configuration-file.html
 * - https://plugins.jetbrains.com/docs/intellij/developing-themes.html
 */

import { ThemeRegistryEntry } from "../../shared/theme-registry";

/**
 * Generate the plugin.xml manifest file content
 *
 * @param themes - Array of theme registry entries
 * @param version - Plugin version
 * @returns XML string for plugin.xml
 */
export function generatePluginXml(
  themes: ThemeRegistryEntry[],
  version: string,
): string {
  const themeProviders = themes
    .map((entry) => {
      const themeId = escapeXml(`bearded-theme-${entry.slug}`);
      // Path is relative to JAR root - no /themes/ prefix needed
      const themePath = escapeXml(`/bearded-theme-${entry.slug}.theme.json`);

      return `    <themeProvider
      id="${themeId}"
      path="${themePath}"
    />`;
    })
    .join("\n");

  return `<!--
  Bearded Theme for JetBrains IDEs
  Generated by Bearded Theme Build System
  https://github.com/BeardedBear/bearded-theme
-->
<idea-plugin>
  <id>com.beardedtheme.jetbrains</id>
  <name>Bearded Theme</name>
  <version>${version}</version>
  <vendor
    email="beardedbearbear@gmail.com"
    url="https://github.com/BeardedBear/bearded-theme"
  >BeardedBear</vendor>

  <description><![CDATA[
    <h1>Bearded Theme</h1>
    <p>The theme with a long beard. A collection of carefully crafted color themes for your IDE.</p>

    <h2>Features</h2>
    <ul>
      <li>60+ theme variants including dark, light, and high contrast options</li>
      <li>Carefully designed color palettes for reduced eye strain</li>
      <li>Consistent syntax highlighting across all supported languages</li>
      <li>Support for the new Islands UI theme style</li>
    </ul>

    <h2>Theme Categories</h2>
    <ul>
      <li><strong>Arc</strong> - Clean, modern dark themes</li>
      <li><strong>Solarized</strong> - Classic solarized color schemes</li>
      <li><strong>Oceanic</strong> - Ocean-inspired color palettes</li>
      <li><strong>Monokai</strong> - Monokai-inspired variants</li>
      <li><strong>Black &amp; Gems</strong> - Pure black backgrounds with gem accent colors</li>
      <li><strong>High Contrast</strong> - Accessibility-focused themes</li>
      <li><strong>Milkshake</strong> - Soft, pastel light themes</li>
      <li><strong>Coffee</strong> - Warm, earthy tones</li>
      <li>And many more...</li>
    </ul>

    <h2>Links</h2>
    <ul>
      <li><a href="https://github.com/BeardedBear/bearded-theme">GitHub Repository</a></li>
      <li><a href="https://github.com/BeardedBear/bearded-theme/issues">Report Issues</a></li>
      <li><a href="https://marketplace.visualstudio.com/items?itemName=BeardedBear.beardedtheme">VS Code Version</a></li>
    </ul>
  ]]></description>

  <change-notes><![CDATA[
    <p>See the <a href="https://github.com/BeardedBear/bearded-theme/releases">GitHub Releases</a> for full changelog.</p>
  ]]></change-notes>

  <idea-version since-build="241"/>

  <depends>com.intellij.modules.platform</depends>

  <extensions defaultExtensionNs="com.intellij">
${themeProviders}
  </extensions>
</idea-plugin>
`;
}

/**
 * Generate a list of theme entries for the plugin
 *
 * @param themes - Array of theme registry entries
 * @returns Array of theme information objects
 */
export function getThemeList(
  themes: ThemeRegistryEntry[],
): Array<{
  dark: boolean;
  id: string;
  name: string;
  path: string;
}> {
  return themes.map((entry) => ({
    dark: !entry.options.light,
    id: `bearded-theme-${entry.slug}`,
    name: `Bearded Theme ${entry.name}`,
    path: `/bearded-theme-${entry.slug}.theme.json`,
  }));
}

/**
 * Escape special XML characters in a string
 *
 * @param str - String to escape
 * @returns XML-safe string
 */
function escapeXml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}
